version: "3.9"

services:
  node0:
    image: cassandra:3.11
    container_name: node0
    hostname: node0
    build:
      context: .
      dockerfile: Dockerfile
    networks: &net
      - cassandra
    environment: &env
      - CASSANDRA_SEEDS=node0 #,node1,node2
      - CASSANDRA_CLUSTER_NAME=cassandra_intro
    # ports:
    #   - 9040:9042
    volumes:
      - ./data:/data
      - ./scripts:/docker-entrypoint-initdb.d

  # node1:
  #   image: cassandra:3.11
  #   container_name: node1
  #   hostname: node1
  #   networks: *net
  #   environment: *env
  #   depends_on:
  #     - node0
  #
  # node2:
  #   image: cassandra:3.11
  #   container_name: node2
  #   hostname: node2
  #   networks: *net
  #   environment: *env
  #   depends_on:
  #     - node1

  rest-service:
    depends_on:
      - node0
    links:
      - node0
    networks: *net
    ports:
      - 8080:3000
    build:
      context: ./cassandra-interaction
      dockerfile: Dockerfile

networks:
  cassandra:
