version: "3.9"

networks:
  lab_9:
    driver: bridge

services:
  spark-master:
    user: root
    image: bitnami/spark:latest
    volumes:
      - "./app:/app"
    working_dir: "/app"
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
    networks:
      - lab_9

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    depends_on:
      - spark-master
    networks:
      - lab_9
